"""add name

Revision ID: 096c9c704e25
Revises: 3692a0162786
Create Date: 2020-09-27 19:09:22.072799

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '096c9c704e25'
down_revision = '3692a0162786'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('applications', sa.Column('name', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('applications', 'name')
    # ### end Alembic commands ###
