"""add groupID

Revision ID: 1c9ff09b7c9c
Revises: 8e9fd2fbb930
Create Date: 2020-09-26 01:37:23.891638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c9ff09b7c9c'
down_revision = '8e9fd2fbb930'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('games', sa.Column('groupID', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('games', 'groupID')
    # ### end Alembic commands ###
