"""switch to bigint

Revision ID: 3692a0162786
Revises: 7915cfe0ac09
Create Date: 2020-09-27 19:03:28.979161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3692a0162786'
down_revision = '7915cfe0ac09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
