"""create applications_games table

Revision ID: 37e43585b228
Revises: 1c9ff09b7c9c
Create Date: 2020-09-26 01:46:25.123229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37e43585b228'
down_revision = '1c9ff09b7c9c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications_games',
    sa.Column('applicationID', sa.BigInteger(), nullable=False),
    sa.Column('gameID', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['applicationID'], ['applications.applicationID'], ),
    sa.ForeignKeyConstraint(['gameID'], ['games.gameID'], ),
    sa.PrimaryKeyConstraint('applicationID', 'gameID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications_games')
    # ### end Alembic commands ###
