"""create application table

Revision ID: 8e9fd2fbb930
Revises: f726b07d949a
Create Date: 2020-09-26 01:36:21.338833

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e9fd2fbb930'
down_revision = 'f726b07d949a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applications',
    sa.Column('applicationID', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.PrimaryKeyConstraint('applicationID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applications')
    # ### end Alembic commands ###
