"""create extension table

Revision ID: fce1a1dc9280
Revises: 
Create Date: 2020-09-25 15:20:28.519846

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fce1a1dc9280'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('extensions',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('isLoaded', sa.Boolean(), server_default="0", nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('extensions')
    # ### end Alembic commands ###
